# Generated by Django 5.2 on 2025-05-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_facility_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(choices=[('standard', 'Standard Room'), ('presidential', '1 Bedroom Presidentail'), ('presidential2', '2 Bedroom Presidential'), ('suite', '1 Bedroom Suite'), ('suite2', '2 Bedroom Suite'), ('executive', 'Executive Deluxe'), ('Deluxe', 'Deluxe Rooms')], max_length=50, unique=True),
        ),
    ]
