# Generated by Django 5.2 on 2025-05-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.CharField(default='DMY', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.CharField(default='DMY', max_length=100),
        ),
    ]
